config/routes.rb
Flightfinder::Application.routes.draw do
  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'

  #get '/home', to: redirect('/')
  scope :api do
   # resources :learninglogs, defaults: {format: :json}
    get "/learninglogs(.:format)" => "learninglogs#index"
    get "/learninglogs/:id(.:format)" => "learninglogs#show"
  end
  root :to => 'high_voltage/pages#show', id: 'home'
end

app/models/learninglog.rb
class Learninglog < ActiveRecord::Base
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/learninglogs_controller.rb
class LearninglogsController < ApplicationController

  def index
    render json: Learninglog.all
  end

  def show
    render json: Learninglog.find(params[:id])
  end

  def learninglog_params
    params.require(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def site_name
    "Flight Finder"
  end

  def site_url
    if Rails.env.production?
      "http://flightfinderapp.herokuapp.com/"
    else
      "http://localhost:3000"
    end
  end

  def meta_author
    "Amber Houle"
  end

  def meta_description
    "Add your website description here"
  end

  def meta_keywords
    # Change the value below between the quotes.
    "Add your keywords here"
  end

  # Returns the full title on a per-page basis.
  # No need to change any of this we set page_title and site_name elsewhere.
  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end

end

app/helpers/learninglogs_helper.rb
module LearninglogsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='LearningLogs'>
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= meta_description %>">
    <meta name="author" content="<%= meta_author %>">
    <meta name="Keywords" content="<%= meta_keywords %>">

    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <a href="#Top"></a>
  </head>
  <body>
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to site_name, site_url, :class => "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
            <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
            <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container theme-showcase">
      <% if current_page?(root_path) %>
        <% if content_for?(:jumbotron) %>
          <div class="jumbotron">
            <%= yield :jumbotron %>
          </div>
        <% end %>
      <% else %>
        <div class="container theme-showcase">
        <% end %>
        <%= yield %>
      </div>

      <footer>
      <hr>
      <p class="pull-right">
      <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
      </p>
      <p>
      &copy; <%= Time.now.year %> <%= site_name %>
    &bull;
    <%= link_to "Privacy", privacy_path %></li>
    &bull;
    <%= link_to "Terms", terms_path %></li>
    </p>
    </footer>
  </div> <!-- /container -->

  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular-resource.min.js"></script>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<% provide(:title, 'Home Page') %>

<% provide(:jumbotron, '
    <h1>Hello, world!</h1>
    <p>WOWOW cool, using rails + bootstrap to build an awesome learning log for junior consultants to track progress!</p>
    <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
'.html_safe)%>

   <div class="input-group input-group-lg">
     <span class="input-group-addon">Learnings &nbsp;&nbsp;&nbsp;&nbsp; </span>

     <input type="text" class="form-control" ng-model="yourName" placeholder="What did you learn?">
   </div>
   <p>Something awesome you learnt this week:</br> {{yourName}}</p>

   <div class="input-group input-group-lg">
     <span class="input-group-addon">Contributions</span>
     <input type="text" class="form-control" ng-model="yourContribution" placeholder="What did you contribute this week??">
   </div>
   <p>Something awesome you contributed this week:</br> {{yourContribution}}</p>

   <div ng-controller="LearninglogsController">
      <ul>
        <li ng-repeat="learninglog in learninglogs">
          <h3>{{learninglog.content}}</h3>
        </li>
      </ul>
   </div>

app/views/pages/privacy.html.erb
<% provide(:title, 'Privacy') %>
<h1>Privacy Policy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<% provide(:title, 'Terms') %>
<h1>Terms of Service</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/welcome/index.html.haml
%h1 Welcome!
%p The time is now:
= Time.now